In [7]:
import pandas as pd

DATA_PATH = "data/"
DATA_FILE = "mid-project-data.csv"
df = pd.read_csv(f"{DATA_FILE}")

features = pd.read_csv(f"{DATA_PATH}numberofseats.csv")
features.head()

  PBLPRFR_PLACE_NM  총판매석  일반판매석  장애인석  OP석  판매유보석
0          CJ 토월극장  1004    842    10   63     89
1           IBK챔버홀   600    594     6    0      0
2            리사이틀홀   354    350     4    0      0
3            오페라극장  2283   1925    20   48    290
4            인춘아트홀   100     98     2    0      0

In [5]:
df = pd.merge(df, features, how="left", on="PBLPRFR_PLACE_NM")
df.head()

,PBLPRFR_NM,PBLPRFR_PLACE_NM,PBLPRFR_DE,PBLPRFR_TIME,GENRE_NM,PRC_CN,HMPG_URL,SETLE_DE,SETLE_TIME,DSCNT_CN,...,MBER_GRAD_NM,BN_VALUE,SEXDSTN_VALUE,OC_AREA_NM,RFN_AT,총판매석,일반판매석,장애인석,OP석,판매유보석
0,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230308,70000,기타 할인,...,무료,50대,F,경기,N,2505.0,2481.0,24.0,0.0,0.0
1,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230221,190000,기타 할인,...,블루,60대,M,서울,N,2505.0,2481.0,24.0,0.0,0.0
2,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230228,10000,기타 할인,...,무료,60대,M,서울,N,2505.0,2481.0,24.0,0.0,0.0
3,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230226,100000,기타 할인,...,무료,40대,M,서울,N,2505.0,2481.0,24.0,0.0,0.0
4,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230320,230000,골드회원 할인40%,...,골드,60대,F,서울,N,2505.0,2481.0,24.0,0.0,0.0

In [11]:
df['총판매석'] = df['총판매석'].astype('Int64')
df['일반판매석'] = df['일반판매석'].astype('Int64')
df['장애인석'] = df['장애인석'].astype('Int64')
df['OP석'] = df['OP석'].astype('Int64')
df['판매유보석'] = df['판매유보석'].astype('Int64')
df.head()

,PBLPRFR_NM,PBLPRFR_PLACE_NM,PBLPRFR_DE,PBLPRFR_TIME,GENRE_NM,PRC_CN,HMPG_URL,SETLE_DE,SETLE_TIME,DSCNT_CN,...,MBER_GRAD_NM,BN_VALUE,SEXDSTN_VALUE,OC_AREA_NM,RFN_AT,총판매석,일반판매석,장애인석,OP석,판매유보석
0,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230308,70000,기타 할인,...,무료,50대,F,경기,N,2505,2481,24,0,0
1,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230221,190000,기타 할인,...,블루,60대,M,서울,N,2505,2481,24,0,0
2,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230228,10000,기타 할인,...,무료,60대,M,서울,N,2505,2481,24,0,0
3,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230226,100000,기타 할인,...,무료,40대,M,서울,N,2505,2481,24,0,0
4,국립합창단 창단 50주년 기념 <한국합창교향곡>,콘서트홀,20230321,193000,합창,R석 30000원 / S석 20000원 / A석 10000원,https://www.sac.or.kr/site/main/show/show_view...,20230320,230000,골드회원 할인40%,...,골드,60대,F,서울,N,2505,2481,24,0,0

In [28]:
cols = ["PBLPRFR_NM", "PBLPRFR_PLACE_NM", "PBLPRFR_DE", "PBLPRFR_TIME"]
agg_dict = {
    "GENRE_NM": "count",
    "SETLE_PRICE": "sum",
    "RFN_AT": lambda x : (x == 'N').sum()
}

df.groupby(cols).agg(agg_dict)

                                                                        GENRE_NM  \
PBLPRFR_NM                    PBLPRFR_PLACE_NM PBLPRFR_DE PBLPRFR_TIME
& Duo의 아름다운 시리즈2              리사이틀홀            20181208   140000              25
'러시아 시즌'선정 <바딤 레핀 바이올린 리사이틀>  콘서트홀             20211017   170000             800
'피아니스트 오윤주의 슈베르티아데' 슈베르트의 환상곡 IBK챔버홀           20170928   200000              37
(공연취소)예술의전당 여름음악축제_Grand duo  리사이틀홀            20220826   193000              56
(렉처 콘서트) 사랑하는 이에게             인춘아트홀            20210915   193000               9
...                                                                          ...
힐링뮤지컬 사랑해 톤즈                  CJ 토월극장          20150717   200000             342
                                               20150718   150000             443
                                                          190000             374
                                               20150719   150000             242
弄弦 농현 전봉초 교수 추모 가족음악회         리사이틀홀            20150503   200000               2

                                                                        SETLE_PRICE  \
PBLPRFR_NM                    PBLPRFR_PLACE_NM PBLPRFR_DE PBLPRFR_TIME
& Duo의 아름다운 시리즈2              리사이틀홀            20181208   140000           366000.0
'러시아 시즌'선정 <바딤 레핀 바이올린 리사이틀>  콘서트홀             20211017   170000         46013000.0
'피아니스트 오윤주의 슈베르티아데' 슈베르트의 환상곡 IBK챔버홀           20170928   200000           841000.0
(공연취소)예술의전당 여름음악축제_Grand duo  리사이틀홀            20220826   193000           955000.0
(렉처 콘서트) 사랑하는 이에게             인춘아트홀            20210915   193000           120000.0
...                                                                             ...
힐링뮤지컬 사랑해 톤즈                  CJ 토월극장          20150717   200000         28039000.0
                                               20150718   150000         39025000.0
                                                          190000         33151000.0
                                               20150719   150000         21273000.0
弄弦 농현 전봉초 교수 추모 가족음악회         리사이틀홀            20150503   200000            10000.0

                                                                        RFN_AT
PBLPRFR_NM                    PBLPRFR_PLACE_NM PBLPRFR_DE PBLPRFR_TIME
& Duo의 아름다운 시리즈2              리사이틀홀            20181208   140000            19
'러시아 시즌'선정 <바딤 레핀 바이올린 리사이틀>  콘서트홀             20211017   170000           454
'피아니스트 오윤주의 슈베르티아데' 슈베르트의 환상곡 IBK챔버홀           20170928   200000            33
(공연취소)예술의전당 여름음악축제_Grand duo  리사이틀홀            20220826   193000             2
(렉처 콘서트) 사랑하는 이에게             인춘아트홀            20210915   193000             9
...                                                                        ...
힐링뮤지컬 사랑해 톤즈                  CJ 토월극장          20150717   200000            69
                                               20150718   150000            54
                                                          190000            59
                                               20150719   150000            37
弄弦 농현 전봉초 교수 추모 가족음악회         리사이틀홀            20150503   200000             2

[16131 rows x 3 columns]