In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
DATA_PATH = "/content/drive/MyDrive/mid_project/"

In [5]:
df = pd.read_csv(f"{DATA_PATH}SAC_ADAVANTK_DATA_202312.csv")
#df.head()

In [6]:
df.shape

(3664663, 16)

In [7]:
df.columns

Index(['PBLPRFR_NM', 'PBLPRFR_PLACE_NM', 'PBLPRFR_DE', 'PBLPRFR_TIME',
       'GENRE_NM', 'PRC_CN', 'HMPG_URL', 'SETLE_DE', 'SETLE_TIME', 'DSCNT_CN',
       'SETLE_PRICE', 'MBER_GRAD_NM', 'BN_VALUE', 'SEXDSTN_VALUE',
       'OC_AREA_NM', 'RFN_AT'],
      dtype='object')

In [8]:
df.columns = ['공연명','공연장소명','공연일자','공연시간','장르명','가격내용','홈페이지URL','결제일자','결제시간','할인내용','결제금액','회원등급명','나이값','성별값','거주지역명','환불여부']

In [9]:
df.drop(['가격내용','홈페이지URL'], axis=1, inplace=True)

In [10]:
import numpy as np

In [11]:
df["성별값_F"] = df["성별값"] == "F"
df["환불여부_Y"] = df["환불여부"] == "Y"

In [12]:
df['성별값_F'] = df['성별값_F'].astype(int)
df['환불여부_Y'] = df['환불여부_Y'].astype(int)

In [13]:
df['나이값'] = df['나이값'].str.extract('(\d+)')

In [14]:
df_filtered = df[df['환불여부_Y'] != 1]

print(df_filtered)

                                공연명 공연장소명      공연일자    공연시간  장르명      결제일자  \
0        국립합창단 창단 50주년 기념 <한국합창교향곡>  콘서트홀  20230321  193000   합창  20230308
1        국립합창단 창단 50주년 기념 <한국합창교향곡>  콘서트홀  20230321  193000   합창  20230221
2        국립합창단 창단 50주년 기념 <한국합창교향곡>  콘서트홀  20230321  193000   합창  20230228
3        국립합창단 창단 50주년 기념 <한국합창교향곡>  콘서트홀  20230321  193000   합창  20230226
4        국립합창단 창단 50주년 기념 <한국합창교향곡>  콘서트홀  20230321  193000   합창  20230320
...                             ...   ...       ...     ...  ...       ...
3664653      로열 콘세르트허바우 오케스트라(4.23)  콘서트홀  20150423  200000  클래식  20141103
3664654      로열 콘세르트허바우 오케스트라(4.23)  콘서트홀  20150423  200000  클래식  20141015
3664656      로열 콘세르트허바우 오케스트라(4.23)  콘서트홀  20150423  200000  클래식  20141015
3664657      로열 콘세르트허바우 오케스트라(4.23)  콘서트홀  20150423  200000  클래식  20150417
3664658      로열 콘세르트허바우 오케스트라(4.23)  콘서트홀  20150423  200000  클래식  20141015

           결제시간        할인내용      결제금액 회원등급명 나이값 성별값 거주지역명 환불여부  성별값_F  환불여부_Y
0         70000       기타 할인   24000.0    무료  50   F    경기    N      1       0
1        190000       기타 할인   10000.0    블루  60   M    서울    N      0       0
2         10000       기타 할인    8000.0    무료  60   M    서울    N      0       0
3        100000       기타 할인   24000.0    무료  40   M    서울    N      0       0
4        230000  골드회원 할인40%   18000.0    골드  60   F    서울    N      1       0
...         ...         ...       ...   ...  ..  ..   ...  ...    ...     ...
3664653  100000       기타 할인  135000.0    블루  60   F    경기    N      1       0
3664654  100000       기타 할인  127500.0    골드  30   M    서울    N      0       0
3664656  100000       기타 할인   72000.0    블루  50   F    충북    N      1       0
3664657  200000       기타 할인  127500.0    골드  30   M    서울    N      0       0
3664658  100000       기타 할인   68000.0    골드  30   M    서울    N      0       0

[1893568 rows x 16 columns]

In [15]:
booking_count_by_time = df['공연시간'].value_counts()

total_bookings = len(df['공연시간'])

booking_ratio_by_time = (booking_count_by_time / total_bookings) * 100

print(booking_ratio_by_time)

공연시간
200000    30.419059
193000    21.718505
170000    11.465393
140000    10.100056
110000     8.076895
150000     8.014025
190000     4.934942
180000     2.125762
160000     0.919539
183000     0.833801
143000     0.648682
213000     0.269329
220000     0.107213
130000     0.100937
194500     0.084646
153000     0.077742
0          0.036920
100000     0.016755
120000     0.012661
163000     0.011897
210000     0.011570
173000     0.003520
161000     0.003111
134000     0.002674
111000     0.002074
123000     0.001392
184000     0.000791
90000      0.000109
Name: count, dtype: float64